### ISSUE TITLE
Add any 2 Medium level Questions from Codeforces

### ISSUE THREAD

**Issue by kamleshjoshi8102** [kamleshjoshi8102/Codeforces_Practice#1]

**Comment by Abhishek-Pant** [comment]
Please Assign me this task as hacktoberfest contributor

**Comment by Abhay-Parihar** [comment]
Please assign me this issue as hacktoberfest contributor

**Comment by shubhamnag14** [comment]
I would to contribute in this repo

**Comment by geoffgeorgein** [comment]
I am Regular CPer please assign me a task

**Comment by Dj9162** [comment]
I am a beginner and I want to work on this issue. Please, Tell me how to do

**Comment by arana2k** [comment]
Please assign me this issue as hacktoberfest contributor
i can give my best to help your issues in cp

**Comment by kamleshjoshi8102** [comment]
Go Ahead @shubhamnag14 @geoffgeorgein @abhishek8778 @Dj9162 

Your Feedback will be Appreciated
:)

**Comment by Jaishree-19** [comment]
I would like to add solutions to this :)

**Comment by kamleshjoshi8102** [comment]
go Ahead @Jaishree-19

**Comment by spyd3r-byte** [comment]
I would Like to add solutions from codeforces

**Comment by aditya-gaikwad** [comment]
Can you please assign me this issue as hacktoberfest contributor. I will definately try my best to solve them.
